config/routes.rb
Rails.application.routes.draw do
  resources :faceapis
  resources :facebookapis
  resources :trainbots
  resources :uttrances
  resources :lists
  resources :wit_key
  resources :wit_entities
  resources :wit_simo
  resources :training


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/facebookapi.rb
class Facebookapi < ApplicationRecord
end

app/controllers/facebookapis_controller.rb
class FacebookapisController < ApplicationController
  before_action :set_facebookapi, only: [:show, :edit, :update, :destroy]

  # GET /facebookapis
  # GET /facebookapis.json
  def index
    @facebookapis = Facebookapi.all
  end

  # GET /facebookapis/1
  # GET /facebookapis/1.json
  def show
  end

  # GET /facebookapis/new
  def new
    @facebookapi = Facebookapi.new
  end

  # GET /facebookapis/1/edit
  def edit
  end

  # POST /facebookapis
  # POST /facebookapis.json
  def create
    @facebookapi = Facebookapi.new(facebookapi_params)

    respond_to do |format|
      if @facebookapi.save
        format.html { redirect_to @facebookapi, notice: 'Facebookapi was successfully created.' }
        format.json { render :show, status: :created, location: @facebookapi }
      else
        format.html { render :new }
        format.json { render json: @facebookapi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebookapis/1
  # PATCH/PUT /facebookapis/1.json
  def update
    respond_to do |format|
      if @facebookapi.update(facebookapi_params)
        format.html { redirect_to @facebookapi, notice: 'Facebookapi was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebookapi }
      else
        format.html { render :edit }
        format.json { render json: @facebookapi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebookapis/1
  # DELETE /facebookapis/1.json
  def destroy
    @facebookapi.destroy
    respond_to do |format|
      format.html { redirect_to facebookapis_url, notice: 'Facebookapi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebookapi
      @facebookapi = Facebookapi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def facebookapi_params
      params.require(:facebookapi).permit(:post, :pheduyet)
    end
end

app/helpers/facebookapis_helper.rb
module FacebookapisHelper
end

app/views/facebookapis/_form.html.erb
<%= form_with(model: facebookapi, local: true) do |form| %>
  <% if facebookapi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(facebookapi.errors.count, "error") %> prohibited this facebookapi from being saved:</h2>

      <ul>
        <% facebookapi.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_field :post %>
  </div>

  <div class="field">
    <%= form.label :pheduyet %>
    <%= form.check_box :pheduyet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/facebookapis/edit.html.erb
<h1>Editing Facebookapi</h1>

<%= render 'form', facebookapi: @facebookapi %>

<%= link_to 'Show', @facebookapi %> |
<%= link_to 'Back', facebookapis_path %>

app/views/facebookapis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facebookapis</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Pheduyet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facebookapis.each do |facebookapi| %>
      <tr>
        <td><%= facebookapi.post %></td>
        <td><%= facebookapi.pheduyet %></td>
        <td><%= link_to 'Show', facebookapi %></td>
        <td><%= link_to 'Edit', edit_facebookapi_path(facebookapi) %></td>
        <td><%= link_to 'Destroy', facebookapi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facebookapi', new_facebookapi_path %>

app/views/facebookapis/new.html.erb
<h1>New Facebookapi</h1>

<%= render 'form', facebookapi: @facebookapi %>

<%= link_to 'Back', facebookapis_path %>

app/views/facebookapis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @facebookapi.post %>
</p>

<p>
  <strong>Pheduyet:</strong>
  <%= @facebookapi.pheduyet %>
</p>

<%= link_to 'Edit', edit_facebookapi_path(@facebookapi) %> |
<%= link_to 'Back', facebookapis_path %>