config/routes.rb
Rails.application.routes.draw do
  resources :faceapis
  resources :facebookapis
  resources :trainbots
  resources :uttrances
  resources :lists
  resources :wit_key
  resources :wit_entities
  resources :wit_simo
  resources :training


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trainbot.rb
class Trainbot < ApplicationRecord
end

app/controllers/trainbots_controller.rb
require 'train'

class TrainbotsController < ApplicationController
  before_action :set_trainbot, only: [:show, :edit, :update, :destroy]

  # GET /trainbots
  # GET /trainbots.json
  def index
    @trainbots = Trainbot.all
  end

  # GET /trainbots/1
  # GET /trainbots/1.json
  def show
  end

  # GET /trainbots/new
  def new
    @trainbot = Trainbot.new
  end

  # GET /trainbots/1/edit
  def edit
  end

  # POST /trainbots
  # POST /trainbots.json
  def create
    @trainbot = Trainbot.new(trainbot_params)
    @org = UttranceService.new
    @org.post_uttrance(trainbot_params[:message],trainbot_params[:intent],trainbot_params[:entity],trainbot_params[:start],trainbot_params[:end],trainbot_params[:body]
    )
    respond_to do |format|
      if @trainbot.save
        format.html { redirect_to @trainbot, notice: 'Trainbot was successfully created.' }
        format.json { render :show, status: :created, location: @trainbot }
      else
        format.html { render :new }
        format.json { render json: @trainbot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainbots/1
  # PATCH/PUT /trainbots/1.json
  def update
    respond_to do |format|
      if @trainbot.update(trainbot_params)
        format.html { redirect_to @trainbot, notice: 'Trainbot was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainbot }
      else
        format.html { render :edit }
        format.json { render json: @trainbot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainbots/1
  # DELETE /trainbots/1.json
  def destroy
    @trainbot.destroy
    respond_to do |format|
      format.html { redirect_to trainbots_url, notice: 'Trainbot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainbot
      @trainbot = Trainbot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trainbot_params
      params.require(:trainbot).permit(:message, :intent, :entity, :start, :end, :body)
    end

end

app/helpers/trainbots_helper.rb
module TrainbotsHelper
end

app/views/trainbots/_form.html.erb
<%= form_with(model: trainbot, local: true) do |form| %>
  <% if trainbot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainbot.errors.count, "error") %> prohibited this trainbot from being saved:</h2>

      <ul>
        <% trainbot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :intent %>
    <%= form.text_field :intent %>
  </div>

  <div class="field">
    <%= form.label :entity %>
    <%= form.text_field :entity %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.text_field :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.text_field :end %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trainbots/edit.html.erb
<h1>Editing Trainbot</h1>

<%= render 'form', trainbot: @trainbot %>

<%= link_to 'Show', @trainbot %> |
<%= link_to 'Back', trainbots_path %>

app/views/trainbots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainbots</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Intent</th>
      <th>Entity</th>
      <th>Start</th>
      <th>End</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainbots.each do |trainbot| %>
      <tr>
        <td><%= trainbot.message %></td>
        <td><%= trainbot.intent %></td>
        <td><%= trainbot.entity %></td>
        <td><%= trainbot.start %></td>
        <td><%= trainbot.end %></td>
        <td><%= trainbot.body %></td>
        <td><%= link_to 'Show', trainbot %></td>
        <td><%= link_to 'Edit', edit_trainbot_path(trainbot) %></td>
        <td><%= link_to 'Destroy', trainbot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainbot', new_trainbot_path %>

app/views/trainbots/new.html.erb
<h1>New Trainbot</h1>

<%= render 'form', trainbot: @trainbot %>

<%= link_to 'Back', trainbots_path %>

app/views/trainbots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @trainbot.message %>
</p>

<p>
  <strong>Intent:</strong>
  <%= @trainbot.intent %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @trainbot.entity %>
</p>

<p>
  <strong>Start:</strong>
  <%= @trainbot.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @trainbot.end %>
</p>

<p>
  <strong>Body:</strong>
  <%= @trainbot.body %>
</p>

<%= link_to 'Edit', edit_trainbot_path(@trainbot) %> |
<%= link_to 'Back', trainbots_path %>