config/routes.rb
Rails.application.routes.draw do
  resources :faceapis
  resources :facebookapis
  resources :trainbots
  resources :uttrances
  resources :lists
  resources :wit_key
  resources :wit_entities
  resources :wit_simo
  resources :training


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/uttrance.rb
class Uttrance < ApplicationRecord
end

app/controllers/uttrances_controller.rb
require 'train'
class UttrancesController < ApplicationController
  before_action :set_uttrance, only: [:show, :edit, :update, :destroy]

  # GET /uttrances
  # GET /uttrances.json
  def index
    @uttrances = Uttrance.all
  end

  # GET /uttrances/1
  # GET /uttrances/1.json
  def show
  end

  # GET /uttrances/new
  def new
    @uttrance = Uttrance.new
  end

  # GET /uttrances/1/edit
  def edit
  end

  # POST /uttrances
  # POST /uttrances.json
  def create

    @uttrance = Uttrance.new(uttrance_params)
    # @uttrance = Uttrance.new(data_facebook)
    respond_to do |format|
      if @uttrance.save
        format.html { redirect_to @uttrance, notice: 'Uttrance was successfully created.' }
        format.json { render :show, status: :created, location: @uttrance }
      else
        format.html { render :new }
        format.json { render json: @uttrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uttrances/1
  # PATCH/PUT /uttrances/1.json
  def update
    respond_to do |format|
      if @uttrance.update(uttrance_params)
        format.html { redirect_to @uttrance, notice: 'Uttrance was successfully updated.' }
        format.json { render :show, status: :ok, location: @uttrance }
      else
        format.html { render :edit }
        format.json { render json: @uttrance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uttrances/1
  # DELETE /uttrances/1.json
  def destroy
    @uttrance.destroy
    respond_to do |format|
      format.html { redirect_to uttrances_url, notice: 'Uttrance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uttrance
      @uttrance = Uttrance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uttrance_params
      params.require(:uttrance).permit(:message, :confidence)
    end
    def data_facebook
      @org = UttranceService.new
      @dl = GraphAPI.new
      datta = @dl.get_data
      datta.each do |t|
        data={
            message: t[:message],
            idd: t[:idd],
            pheduyet: @org.get_uttrance(t[:message])
        }
        return data
      end
      # if @org.get_uttrance(uttrance_params[:message])
      #   data={
      #       message: uttrance_params[:message],
      #       confidence: @org.get_uttrance(uttrance_params[:message])
      #   }
      # else
      #   data={
      #       message: uttrance_params[:message],
      #       confidence: 0
      #   }
      # end
    end
end

app/helpers/uttrances_helper.rb
module UttrancesHelper
end

app/views/uttrances/_form.html.erb
<%= form_with(model: uttrance, local: true) do |form| %>
  <% if uttrance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uttrance.errors.count, "error") %> prohibited this uttrance from being saved:</h2>

      <ul>
        <% uttrance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :confidence %>
    <%#= form.text_field :confidence %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uttrances/edit.html.erb
<h1>Editing Uttrance</h1>

<%= render 'form', uttrance: @uttrance %>

<%= link_to 'Show', @uttrance %> |
<%= link_to 'Back', uttrances_path %>

app/views/uttrances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uttrances</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Confidence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uttrances.each do |uttrance| %>
      <tr>
        <td><%= uttrance.message %></td>
        <td><%= uttrance.confidence %></td>
        <td><%= link_to 'Show', uttrance %></td>
        <td><%= link_to 'Edit', edit_uttrance_path(uttrance) %></td>
        <td><%= link_to 'Destroy', uttrance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uttrance', new_uttrance_path %>

app/views/uttrances/new.html.erb
<h1>New Uttrance</h1>

<%= render 'form', uttrance: @uttrance %>

<%= link_to 'Back', uttrances_path %>

app/views/uttrances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @uttrance.message %>
</p>

<p>
  <strong>Confidence:</strong>
  <%= @uttrance.confidence %>
</p>

<%= link_to 'Edit', edit_uttrance_path(@uttrance) %> |
<%= link_to 'Back', uttrances_path %>